---
# tasks file
# https://docs.openstack.org/install-guide/openstack-services.html
# https://docs.openstack.org/cinder/train/install/cinder-controller-install-rdo.html
# https://docs.openstack.org/train/install/

  - include_vars: "{{ playbook_dir }}/config.yml"
  - include_vars: "{{ playbook_dir }}/passwords.yml"
  - include_vars: "main.yml"

  - name: Create database and user
    shell: |
      mysql -u root -p{{ ROOT_DBPASS }} -e "DROP DATABASE cinder;"
      mysql -u root -p{{ ROOT_DBPASS }} -e "CREATE DATABASE cinder;"
      mysql -u root -p{{ ROOT_DBPASS }} -e "GRANT ALL PRIVILEGES ON cinder.* TO 'cinder'@'localhost' IDENTIFIED BY '{{ CINDER_DBPASS }}';"
      mysql -u root -p{{ ROOT_DBPASS }} -e "GRANT ALL PRIVILEGES ON cinder.* TO 'cinder'@'%' IDENTIFIED BY '{{ CINDER_DBPASS }}';"

  - name: Create user
    shell: |
      source /root/admin-openrc
      openstack user create --domain default --password {{ CINDER_PASS }} cinder  
    args: 
      executable: /bin/bash             
    
  - name: Add the admin role to the cinder user
    shell: |
      source /root/admin-openrc
      openstack role add --project service --user cinder admin
    args: 
      executable: /bin/bash          
  
  - name: Create the cinder service entity
    shell: |
      source /root/admin-openrc
      openstack service create --name cinderv2 --description "OpenStack Block Storage" volumev2
      openstack service create --name cinderv3 --description "OpenStack Block Storage" volumev3  
      openstack endpoint create --region RegionOne volumev2 public https://{{ openstack.controller.name }}:{{ item.remote_port }}/v2/%\(project_id\)s 
      openstack endpoint create --region RegionOne volumev2 internal https://{{ openstack.controller.name }}:{{ item.remote_port }}/v2/%\(project_id\)s  
      openstack endpoint create --region RegionOne volumev2 admin https://{{ openstack.controller.name }}:{{ item.remote_port }}/v2/%\(project_id\)s
      openstack endpoint create --region RegionOne volumev3 public https://{{ openstack.controller.name }}:{{ item.remote_port }}/v3/%\(project_id\)s   
      openstack endpoint create --region RegionOne volumev3 internal https://{{ openstack.controller.name }}:{{ item.remote_port }}/v3/%\(project_id\)s   
      openstack endpoint create --region RegionOne volumev3 admin https://{{ openstack.controller.name }}:{{ item.remote_port }}/v3/%\(project_id\)s  
    args: 
      executable: /bin/bash  
    loop:
      "{{ openstack.services }}"
    when:
      - item.name == "cinder"                                    
       
  - name: Installing the packages
    apt:
      name: "{{ packages }}"
      state: latest
    register: apt_res
    retries: 300
    delay: 10
    until: apt_res is success      
    vars:
      packages:
        - cinder-api
        - cinder-scheduler
  
  - name: Edit the /etc/cinder/cinder.conf file 
    template:
      src: cinder.conf.j2
      dest: /etc/cinder/cinder.conf
      owner: root 
      group: cinder
      mode: '0640'
  
  - name: Populate the database
    shell: |
      su -s /bin/sh -c "cinder-manage db sync" cinder
    args:

  - name: Edit the /etc/nova/nova.conf
    template:
      src: nova.conf.j2
      dest: /etc/nova/nova.conf
      owner: root 
      group: nova
      mode: '0640'      
    vars:
      local_port: "{{ item.local_port }}"
      local_ip: "{{ item.local_ip }}"
      remote_port: "{{ item.remote_port }}"
    loop:
      "{{ openstack.services }}"
    when:
      - item.name == "nova"        
    
  - name: Edit cinder wsgi file
    template:
      src: cinder-wsgi.conf.j2
      dest: /etc/apache2/conf-available/cinder-wsgi.conf

  - name: Create a symbolic link
    ansible.builtin.file:
      src: /etc/apache2/conf-available/cinder-wsgi.conf
      dest: /etc/apache2/conf-enabled/cinder-wsgi.conf
      state: link   
      
  - name: Start the Block Storage services and configure them to start when the system boots
    systemd:
      name: "{{ item }}"
      enabled: yes
      state: restarted
    with_items:
      - cinder-scheduler
      - apache2
      - nova-api
    
      
      




    


