---
# tasks file for 02_ntp
  - include_vars: "{{ playbook_dir }}/config.yml"
  - include_vars: "main.yml"
  

  - name: Update system
    apt:
      name: '*'
      state: 'latest'
      update_cache: yes
    retries: 300
    delay: 10

  - name: Check if reboot required
    stat:
      path: /var/run/reboot-required
    register: reboot_required_file    

  - name: Reboot
    reboot:
      msg: Reboot triggered
      reboot_timeout: 360
    when: reboot_required_file.stat.exists == true

  - name: Uninstall Chrony 
    apt:
      name: chrony
      state: absent
    register: apt_res
    retries: 300
    delay: 10
    until: apt_res is success      
  
  - name: Install Chrony
    apt:
      name: chrony
      state: latest
    register: apt_res
    retries: 300
    delay: 10
    until: apt_res is success      
  
  - name: Configure Chrony
    template:
      src: chrony.conf.j2
      dest: /etc/chrony/chrony.conf
      owner: root
      group: root
      mode: '0640'
  
  - name: Enable and start Chrony
    systemd:
      name: chrony
      enabled: yes
      state: restarted
    


