---
# tasks file
# https://docs.openstack.org/install-guide/environment-packages-ubuntu.html
# When installing the Train release, run:

  - include_vars: "{{ playbook_dir }}/config.yml" 
  - include_vars: "main.yml"
  
  - name: Add repository
    shell: |
      apt-add-repository -y cloud-archive:{{ openstack.release }}  

    register: apt_res
    retries: 300
    delay: 10
    until: apt_res is success
    args:

  - name: Installing the openstack release
    apt:
      name: "{{ pkg }}"
      state: latest
    register: apt_res
    retries: 300
    delay: 10
    until: apt_res is success      
    vars:
      pkg:
        - software-properties-common
  
  - name: Upgrade the packages on all nodes
    apt:
      name: '*'
      state: latest
    register: apt_res
    retries: 300
    delay: 10
    until: apt_res is success      

  - name: Install the  OpenStack client
    apt:
      name: python3-openstackclient
      state: latest
    register: apt_res
    retries: 300
    delay: 10
    until: apt_res is success      



